name: 'Hello World'
description: 'あいさつして、あいさつした時間を表示する'
inputs:
  who-to-greet:
    description: 'あいさつする相手'
    required: true
    default: '世界'
outputs:
  time:
    description: 'あいさつした時間'
runs:
  using: 'node16'
  main: 'dist/index.js'
